name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}  # Use your PAT secret here
        repository: Raminpahnabi/CE321
        ssh-strict: true
        persist-credentials: true
        clean: true
        sparse-checkout-cone-mode: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        set-safe-directory: true
      #with:
        #submodules: recursive
        #token: ${{ secrets.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 }}  # Use the token if you need additional permissions

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Change this to your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests
       

