name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.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 }}  # Use the token if you need additional permissions

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Change this to your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests
       

